(()=>{'use strict';
const c=document.getElementById('game'),x=c.getContext('2d');
const ui={hp:document.getElementById('hp'),weapon:document.getElementById('weapon'),ammo:document.getElementById('ammo'),intel:document.getElementById('intel'),kills:document.getElementById('kills'),status:document.getElementById('status'),objective:document.getElementById('objective'),overlay:document.getElementById('overlay'),start:document.getElementById('startBtn'),reload:document.getElementById('reloadBtn'),swap:document.getElementById('swapBtn'),med:document.getElementById('medBtn')};
const W={w:2400,h:1500};
const walls=[{x:300,y:180,w:430,h:60},{x:300,y:240,w:60,h:330},{x:840,y:120,w:70,h:460},{x:1080,y:250,w:420,h:65},{x:1440,y:315,w:65,h:330},{x:1680,y:130,w:70,h:420},{x:1960,y:260,w:300,h:65},{x:420,y:820,w:430,h:65},{x:790,y:885,w:65,h:300},{x:1030,y:760,w:70,h:410},{x:1280,y:900,w:400,h:65},{x:1620,y:965,w:65,h:320},{x:1900,y:790,w:70,h:400},{x:2130,y:930,w:70,h:300}];
const intelPts=[[650,500],[1320,540],[2030,1180]],extract={x:2260,y:1340,r:70};
const defs={pistol:{name:'Pistol',mag:12,dmg:38,rate:.23,vel:900,spread:.035,reload:1.15},rifle:{name:'Rifle',mag:30,dmg:24,rate:.095,vel:1050,spread:.055,reload:1.55}};
let p,enemies,shots,pickups,fx,run=false,last=0,raf=0,kills=0,intel=0,move={x:0,y:0},aim={x:1,y:0},firing=false;
function player(){return{x:120,y:120,r:15,hp:100,speed:260,gun:'pistol',meds:2,inv:0,cd:0,reloading:0,guns:{pistol:{a:12,r:48},rifle:{a:30,r:90}}}}
function guards(){return[[520,360],[780,650],[1030,430],[1270,390],[1570,520],[1880,440],[2180,520],[600,1040],[980,1270],[1390,1160],[1810,1240],[2150,980]].map((q,i)=>({x:q[0],y:q[1],hx:q[0],hy:q[1],r:i%5?14:17,hp:i%5?55:90,speed:i%5?95:76,a:Math.random()*6.28,t:1+Math.random()*2,alert:0,cd:Math.random(),heavy:i%5===0}))}
function reset(){p=player();enemies=guards();shots=[];fx=[];kills=0;intel=0;pickups=intelPts.map(q=>({x:q[0],y:q[1],type:'intel',r:11}));pickups.push({x:950,y:650,type:'ammo',r:10},{x:1760,y:680,type:'ammo',r:10},{x:1530,y:1300,type:'med',r:10});move={x:0,y:0};aim={x:1,y:0};firing=false;hud()}
function hud(){let g=p.guns[p.gun];ui.hp.textContent=Math.max(0,Math.ceil(p.hp));ui.weapon.textContent=defs[p.gun].name;ui.ammo.textContent=g.a+' / '+g.r;ui.intel.textContent=intel+' / 3';ui.kills.textContent=kills;ui.med.textContent='MED ×'+p.meds;ui.objective.textContent=intel>=3?'EXTRAKTION ERREICHEN':'3 INTEL SICHERN'}
function blocked(cx,cy,r){for(const w of walls){let nx=Math.max(w.x,Math.min(cx,w.x+w.w)),ny=Math.max(w.y,Math.min(cy,w.y+w.h)),dx=cx-nx,dy=cy-ny;if(dx*dx+dy*dy<r*r)return true}return false}
function moveObj(o,dx,dy){let nx=Math.max(o.r,Math.min(W.w-o.r,o.x+dx));if(!blocked(nx,o.y,o.r))o.x=nx;let ny=Math.max(o.r,Math.min(W.h-o.r,o.y+dy));if(!blocked(o.x,ny,o.r))o.y=ny}
function fire(){if(!run||p.cd>0||p.reloading>0)return;let g=p.guns[p.gun],d=defs[p.gun];if(g.a<=0){reload();return}g.a--;p.cd=d.rate;let a=Math.atan2(aim.y,aim.x)+(Math.random()-.5)*d.spread;shots.push({x:p.x,y:p.y,vx:Math.cos(a)*d.vel,vy:Math.sin(a)*d.vel,r:3,dmg:d.dmg,life:1.3,bad:false});burst(p.x+aim.x*20,p.y+aim.y*20,3);hud()}
function enemyFire(e){let dx=p.x-e.x,dy=p.y-e.y,a=Math.atan2(dy,dx)+(Math.random()-.5)*.13;shots.push({x:e.x,y:e.y,vx:Math.cos(a)*480,vy:Math.sin(a)*480,r:3,dmg:e.heavy?18:12,life:1.8,bad:true});e.cd=e.heavy?.72:1.0}
function reload(){if(p.reloading>0)return;let g=p.guns[p.gun],d=defs[p.gun];if(g.a>=d.mag||g.r<=0)return;p.reloading=d.reload;ui.reload.textContent='...'}
function finishReload(){let g=p.guns[p.gun],d=defs[p.gun],n=Math.min(d.mag-g.a,g.r);g.a+=n;g.r-=n;ui.reload.textContent='R';hud()}
function swap(){if(p.reloading>0)return;p.gun=p.gun==='pistol'?'rifle':'pistol';hud()}
function med(){if(p.meds&&p.hp<100){p.meds--;p.hp=Math.min(100,p.hp+45);hud()}}
function burst(px,py,n){for(let i=0;i<n;i++)fx.push({x:px,y:py,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,l:.25})}
function update(dt){p.cd=Math.max(0,p.cd-dt);p.inv=Math.max(0,p.inv-dt);if(p.reloading>0&&(p.reloading-=dt)<=0){p.reloading=0;finishReload()}if(move.x||move.y)moveObj(p,move.x*p.speed*dt,move.y*p.speed*dt);if(firing)fire();let alerted=0;
for(const e of enemies){e.cd=Math.max(0,e.cd-dt);e.t-=dt;let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d<340)e.alert=5;if(e.alert>0){e.alert-=dt;alerted++;let nx=dx/d,ny=dy/d;if(d>175)moveObj(e,nx*e.speed*dt,ny*e.speed*dt);else if(d<115)moveObj(e,-nx*e.speed*.6*dt,-ny*e.speed*.6*dt);if(d<390&&e.cd<=0)enemyFire(e)}else{if(e.t<=0){e.a+=(Math.random()-.5)*2.8;e.t=1+Math.random()*2.5}moveObj(e,Math.cos(e.a)*e.speed*.3*dt,Math.sin(e.a)*e.speed*.3*dt);if(Math.hypot(e.x-e.hx,e.y-e.hy)>150)e.a=Math.atan2(e.hy-e.y,e.hx-e.x)}}ui.status.textContent=alerted?'ALERT':'STEALTH';ui.status.style.color=alerted?'#ff7373':'#83e0a2';
for(let i=shots.length-1;i>=0;i--){let b=shots[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||blocked(b.x,b.y,b.r)||b.x<0||b.y<0||b.x>W.w||b.y>W.h){shots.splice(i,1);continue}if(b.bad){if(Math.hypot(b.x-p.x,b.y-p.y)<b.r+p.r&&p.inv<=0){p.hp-=b.dmg;p.inv=.16;burst(p.x,p.y,5);shots.splice(i,1);if(p.hp<=0){p.hp=0;hud();end(false);return}}}else for(let j=enemies.length-1;j>=0;j--){let e=enemies[j];if(Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e.hp-=b.dmg;e.alert=5;burst(e.x,e.y,5);shots.splice(i,1);if(e.hp<=0){kills++;if(Math.random()<.28)pickups.push({x:e.x,y:e.y,type:Math.random()<.75?'ammo':'med',r:10});enemies.splice(j,1)}break}}}
for(let i=pickups.length-1;i>=0;i--){let q=pickups[i];if(Math.hypot(p.x-q.x,p.y-q.y)<p.r+q.r+7){if(q.type==='intel')intel++;else if(q.type==='ammo'){p.guns.pistol.r+=12;p.guns.rifle.r+=30}else p.meds=Math.min(4,p.meds+1);pickups.splice(i,1);hud()}}
for(let i=fx.length-1;i>=0;i--){let f=fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;if((f.l-=dt)<=0)fx.splice(i,1)}if(intel>=3&&Math.hypot(p.x-extract.x,p.y-extract.y)<extract.r)end(true);hud()}
function cam(){let ar=c.width/c.height,vh=720,vw=vh*ar;return{x:Math.max(0,Math.min(W.w-vw,p.x-vw/2)),y:Math.max(0,Math.min(W.h-vh,p.y-vh/2)),w:vw,h:vh}}
function circle(px,py,r,col){x.beginPath();x.arc(px,py,r,0,6.283);x.fillStyle=col;x.fill()}
function draw(){let C=cam(),sx=c.width/C.w,sy=c.height/C.h;x.setTransform(sx,0,0,sy,-C.x*sx,-C.y*sy);x.fillStyle='#0b1016';x.fillRect(C.x,C.y,C.w,C.h);x.strokeStyle='#ffffff09';x.lineWidth=1;for(let gx=0;gx<W.w;gx+=60){x.beginPath();x.moveTo(gx,0);x.lineTo(gx,W.h);x.stroke()}for(let gy=0;gy<W.h;gy+=60){x.beginPath();x.moveTo(0,gy);x.lineTo(W.w,gy);x.stroke()}x.fillStyle='#26313a';for(const w of walls){x.fillRect(w.x,w.y,w.w,w.h);x.strokeStyle='#ffffff18';x.strokeRect(w.x,w.y,w.w,w.h)}circle(extract.x,extract.y,extract.r,intel>=3?'#4ebd7940':'#4ebd7910');x.strokeStyle='#62d78b';x.lineWidth=4;x.beginPath();x.arc(extract.x,extract.y,extract.r,0,6.283);x.stroke();for(const q of pickups)circle(q.x,q.y,q.r,q.type==='intel'?'#e7ca55':q.type==='ammo'?'#559bd8':'#eef2f5');for(const b of shots)circle(b.x,b.y,b.r,b.bad?'#ff6868':'#fff');for(const e of enemies){if(e.alert>0){x.strokeStyle='#ff55554a';x.lineWidth=2;x.beginPath();x.arc(e.x,e.y,28,0,6.283);x.stroke()}circle(e.x,e.y,e.r,e.heavy?'#b9425b':'#d95858')}for(const f of fx)circle(f.x,f.y,2,'#fff');circle(p.x,p.y,p.r,p.inv?'#a5d5ff':'#54a8dd');x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.moveTo(p.x,p.y);x.lineTo(p.x+aim.x*30,p.y+aim.y*30);x.stroke();x.setTransform(1,0,0,1,0,0)}
function resize(){let d=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;c.width=Math.floor(w*d);c.height=Math.floor(h*d);draw()}addEventListener('resize',resize,{passive:true});
function loop(t){if(!run)return;let dt=Math.min((t-last)/1000,.033);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}function start(){reset();run=true;ui.overlay.classList.remove('show');last=performance.now();raf=requestAnimationFrame(loop)}function end(win){run=false;cancelAnimationFrame(raf);ui.overlay.querySelector('h1').textContent=win?'EXTRACTION COMPLETE':'MISSION FAILED';ui.overlay.querySelector('p').textContent=win?`Intel gesichert. ${kills} Gegner ausgeschaltet.`:`Agent ausgeschaltet. ${kills} Gegner ausgeschaltet.`;ui.start.textContent='NOCHMAL';ui.overlay.classList.add('show');draw()}
function stick(el,onMove,onEnd){let knob=el.querySelector('.stickKnob'),id=null;function set(e){let r=el.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=r.width*.32,d=Math.hypot(dx,dy)||1,n=Math.min(d,m),nx=dx/d,ny=dy/d;knob.style.transform=`translate(${nx*n}px,${ny*n}px)`;onMove(nx,ny,d/m)}el.addEventListener('pointerdown',e=>{e.preventDefault();id=e.pointerId;el.setPointerCapture(id);set(e)});el.addEventListener('pointermove',e=>{if(e.pointerId===id){e.preventDefault();set(e)}});function up(e){if(e.pointerId!==id)return;id=null;knob.style.transform='translate(0,0)';onEnd()}el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)}
stick(document.getElementById('leftStick'),(a,b,m)=>{move=m>.12?{x:a,y:b}:{x:0,y:0}},()=>move={x:0,y:0});stick(document.getElementById('rightStick'),(a,b,m)=>{if(m>.12){aim={x:a,y:b};firing=true}},()=>firing=false);ui.start.addEventListener('click',start);ui.reload.addEventListener('click',reload);ui.swap.addEventListener('click',swap);ui.med.addEventListener('click',med);document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault());reset();resize();
})();
